#!/usr/bin/env sh
set -u
type curl > /dev/null || { echo "curl: not found"; exit 1; }


repo='longbridgeapp/longbridge-terminal'
bin_name='longbridge'
version='0.1.4'

platform="$(uname | tr "[A-Z]" "[a-z]")"  # Linux => linux
arch="$(uname -m | sed 's/x86_64/amd64/')"  # x86_64 => amd64

if [ "$platform" = "darwin" ]; then
  platform="mac"
  arch="universal"
else 
  echo "Sorry, Longbridge Terminal is only support macOS in current."
  echo ""
  echo "We will release the Linux support soon, please watch the updates on GitHub."
  echo "https://github.com/longbridgeapp/longbridge-terminal"
  exit
fi

echo "Downloading $bin_name@$version ..."

libc=''
if ldd --version 2>&1 | grep -q 'musl'; then
  libc='-musl'
fi

curl -Lo $bin_name.tar.gz https://download.lbkrs.com/longbridge-tui/prod-$version/$platform/$arch/$bin_name.tar.gz
tar zxf $bin_name.tar.gz

if test $(id -u) -eq 0; then
  mv $bin_name /usr/local/bin/$bin_name
else
  sudo mv $bin_name /usr/local/bin/$bin_name
fi

rm $bin_name.tar.gz
echo "Longbridge Terminal $version has installed successfully."
echo ""
echo "You can use `longbridge -h` to get help."
echo ""